### ISSUE TITLE
Add SelectedItem and extend Go Template engine with Sprig Functions

### ISSUE THREAD

**Issue by SebTardif** [kubemod/kubemod#48]
Hi,

I would like a way to be able to substitute string like base url of images to point to own docker images repo. Maybe a valid transformation could be to allow do regex substitution?

Even more flexible, would be about be able to call custom code (running in an image). 

I like Kubemod, but it doesn't take much to get use cases that are not supported.

**Comment by vassilvk** [comment]
Hi @SebTardif,

The `value` part of a ModRule's `patch` operation is a [Golang template](https://github.com/kubemod/kubemod#golang-template).
You can implement any transformation logic - the result of evaluating the template will be used for the JSON Patch operation.

That said, in order to implement your use case, there are two pieces missing:
- Documentation about how to access the result of the patch operation's `select` expression from within a `value` Golang template.
- The ability to perform regex replacements through extending the Go Template infrastructure with something like the [Sprig Functions library](http://masterminds.github.io/sprig/). This will unlock functions such as `regexReplaceAll` ([see here](http://masterminds.github.io/sprig/strings.html)).

I suggest that we change the title of this issue to: `Extend value Go Template engine with Sprig Functions`.
I can then add Sprig to the mix and add some examples that cover your use case.

**Comment by vassilvk** [comment]
@SebTardif, this is complete and released as KubeMod v0.11.0.

You can see an example of replacing the repository part of an image here: https://github.com/kubemod/kubemod#advanced-use-of-selecteditem
