### ISSUE TITLE
Introduce TargetNamespaceRegex as a way to target resources across namespaces

### ISSUE THREAD

**Issue by jamiecore** [kubemod/kubemod#51]
Today it appears that rules in `kubemod-system` apply to non-namespaced resources

I would like to be able to create 1 ModRule in kubemod-system for namespaced resources (Deployment, Pod, Service) and have it apply to resources created in any namespace

**Comment by vassilvk** [comment]
@jamiecore, thank you for the PRs.

I have reviewed them and I have two concerns:

1. KubeMod is quite promiscuous as it must listen to create/update requests for a large list of resource types. If we let **all** ModRules in `kubemod-system` apply to **all** resources passed through KubeMod, things may become busy (CPU-wise).
2. Patching the namespace into the original object's metadata in order to make `IsMatch` work, may interfere with the downstream logic which may not expect a namespace. I know you've done your homework with the tests, but I'd like to keep the `jsonv` object passed to `IsMatch` as close to the original objects received by the webhook as possible.

I have an alternative suggestion:

We can introduce a new string field in the `spec` section of the `ModRule` resource: `targetNamespaceRegex`.
This field will be optional and will only apply to ModRules deployed to `kubemod-system`.

The matching logic for ModRules deployed to `kubemod-system` then becomes:
- When the field is not set, or is set to `.*`, the ModRule applies to all non-namespaced resources and is subject to further `IsMatch` filtering.
- When the field is set, it is matched against the namespace of the incoming resources and the ModRule's deep `IsMatch` is performed only when the cheap `targetNamespaceRegex` match is positive.

This way you accomplished both your requirements to deploy cluter-wide ModRules that target namespaced and non-namespaced objects as well as maintain a fine-grained control over which exact namespaces to target with those ModRules.

Of course a user can set `targetNamespaceRegex` to `.*` on all their `kubemod-system` ModRules and kill their cluster's performance, but at least we are not doing that by default.

Thoughts?

**Comment by jamiecore** [comment]
I like!!  Gimme a few

Just to clarify -- the matching logic for ModRules deployed to kubemod-system then becomes:

    When the field is not set, the ModRule applies to all non-namespaced resources and is subject to further IsMatch filtering.
    When the field is set to .*, the ModRule applies to all namespaced and non-namespaced resources and is subject to further IsMatch filtering.
    When the field is set to .+, the ModRule applies to all namespaced resources and is subject to further IsMatch filtering.
    When the field is set, it is matched against the namespace of the incoming resources and the ModRule's deep IsMatch is performed only when the cheap targetNamespaceRegex match is positive.

**Comment by jamiecore** [comment]
closing previous PRs

**Comment by vassilvk** [comment]
You got it 100% 👍
